-- Poblar la base de datos con datos de ejemplo para el generador de exámenes de inglés

-- Verbos (100 irregulares)
INSERT INTO verbo (infinitivo, pasado_simple, participio_pasado, significado) VALUES
('arise', 'arose', 'arisen', 'surgir'),
('awake', 'awoke', 'awoken', 'despertar'),
('be', 'was/were', 'been', 'ser/estar'),
('bear', 'bore', 'born', 'soportar/nacer'),
('beat', 'beat', 'beaten', 'golpear'),
('become', 'became', 'become', 'convertirse'),
('begin', 'began', 'begun', 'empezar'),
('bend', 'bent', 'bent', 'doblar'),
('bet', 'bet', 'bet', 'apostar'),
('bind', 'bound', 'bound', 'atar'),
('bite', 'bit', 'bitten', 'morder'),
('bleed', 'bled', 'bled', 'sangrar'),
('blow', 'blew', 'blown', 'soplar'),
('break', 'broke', 'broken', 'romper'),
('bring', 'brought', 'brought', 'traer'),
('broadcast', 'broadcast', 'broadcast', 'transmitir'),
('build', 'built', 'built', 'construir'),
('burn', 'burnt', 'burnt', 'quemar'),
('burst', 'burst', 'burst', 'estallar'),
('buy', 'bought', 'bought', 'comprar'),
('catch', 'caught', 'caught', 'atrapar'),
('choose', 'chose', 'chosen', 'elegir'),
('come', 'came', 'come', 'venir'),
('cost', 'cost', 'cost', 'costar'),
('cut', 'cut', 'cut', 'cortar'),
('deal', 'dealt', 'dealt', 'negociar'),
('dig', 'dug', 'dug', 'cavar'),
('do', 'did', 'done', 'hacer'),
('draw', 'drew', 'drawn', 'dibujar'),
('dream', 'dreamt', 'dreamt', 'soñar'),
('drink', 'drank', 'drunk', 'beber'),
('drive', 'drove', 'driven', 'conducir'),
('eat', 'ate', 'eaten', 'comer'),
('fall', 'fell', 'fallen', 'caer'),
('feed', 'fed', 'fed', 'alimentar'),
('feel', 'felt', 'felt', 'sentir'),
('fight', 'fought', 'fought', 'pelear'),
('find', 'found', 'found', 'encontrar'),
('fly', 'flew', 'flown', 'volar'),
('forbid', 'forbade', 'forbidden', 'prohibir'),
('forget', 'forgot', 'forgotten', 'olvidar'),
('forgive', 'forgave', 'forgiven', 'perdonar'),
('freeze', 'froze', 'frozen', 'congelar'),
('get', 'got', 'gotten', 'obtener'),
('give', 'gave', 'given', 'dar'),
('go', 'went', 'gone', 'ir'),
('grow', 'grew', 'grown', 'crecer'),
('hang', 'hung', 'hung', 'colgar'),
('have', 'had', 'had', 'tener'),
('hear', 'heard', 'heard', 'oír'),
('hide', 'hid', 'hidden', 'esconder'),
('hit', 'hit', 'hit', 'golpear'),
('hold', 'held', 'held', 'sostener'),
('hurt', 'hurt', 'hurt', 'herir'),
('keep', 'kept', 'kept', 'mantener'),
('know', 'knew', 'known', 'saber/conocer'),
('lay', 'laid', 'laid', 'poner'),
('lead', 'led', 'led', 'liderar'),
('leave', 'left', 'left', 'dejar'),
('lend', 'lent', 'lent', 'prestar'),
('let', 'let', 'let', 'permitir'),
('lie', 'lay', 'lain', 'yacer'),
('light', 'lit', 'lit', 'encender'),
('lose', 'lost', 'lost', 'perder'),
('make', 'made', 'made', 'hacer/fabricar'),
('mean', 'meant', 'meant', 'significar'),
('meet', 'met', 'met', 'encontrar'),
('pay', 'paid', 'paid', 'pagar'),
('put', 'put', 'put', 'poner'),
('read', 'read', 'read', 'leer'),
('ride', 'rode', 'ridden', 'montar'),
('ring', 'rang', 'rung', 'sonar'),
('rise', 'rose', 'risen', 'elevarse'),
('run', 'ran', 'run', 'correr'),
('say', 'said', 'said', 'decir'),
('see', 'saw', 'seen', 'ver'),
('sell', 'sold', 'sold', 'vender'),
('send', 'sent', 'sent', 'enviar'),
('set', 'set', 'set', 'colocar'),
('shake', 'shook', 'shaken', 'sacudir'),
('shine', 'shone', 'shone', 'brillar'),
('shoot', 'shot', 'shot', 'disparar'),
('show', 'showed', 'shown', 'mostrar'),
('shut', 'shut', 'shut', 'cerrar'),
('sing', 'sang', 'sung', 'cantar'),
('sink', 'sank', 'sunk', 'hundir'),
('sit', 'sat', 'sat', 'sentarse'),
('sleep', 'slept', 'slept', 'dormir'),
('speak', 'spoke', 'spoken', 'hablar'),
('spend', 'spent', 'spent', 'gastar'),
('stand', 'stood', 'stood', 'estar de pie'),
('steal', 'stole', 'stolen', 'robar'),
('stick', 'stuck', 'stuck', 'pegar'),
('strike', 'struck', 'struck', 'golpear'),
('swear', 'swore', 'sworn', 'jurar'),
('sweep', 'swept', 'swept', 'barrer'),
('swim', 'swam', 'swum', 'nadar'),
('take', 'took', 'taken', 'tomar/llevar'),
('teach', 'taught', 'taught', 'enseñar'),
('tear', 'tore', 'torn', 'romper'),
('tell', 'told', 'told', 'contar/decir'),
('think', 'thought', 'thought', 'pensar'),
('throw', 'threw', 'thrown', 'lanzar'),
('understand', 'understood', 'understood', 'entender'),
('wake', 'woke', 'woken', 'despertar'),
('wear', 'wore', 'worn', 'llevar puesto'),
('win', 'won', 'won', 'ganar'),
('write', 'wrote', 'written', 'escribir');

-- Tiempos verbales
INSERT INTO tiempo_verbal (nombre, descripcion) VALUES
('Presente Simple', 'Acciones habituales o verdades generales'),
('Pasado Simple', 'Acciones completadas en el pasado'),
('Presente Perfecto', 'Acciones que ocurrieron en un tiempo no especificado antes de ahora'),
('Futuro Simple', 'Acciones que ocurrirán en el futuro'),
('Presente Continuo', 'Acciones que están ocurriendo ahora'),
('Pasado Continuo', 'Acciones que estaban ocurriendo en un momento específico del pasado');

-- Examen de ejemplo
INSERT INTO examen (fecha_creacion) VALUES (NOW());

-- Preguntas de ejemplo (mismo verbo en ambas frases, variando tipo y tiempo, en diálogo)
INSERT INTO pregunta (frase1, frase2, tiempo_verbal1_id, tiempo_verbal2_id, afirmativa, verbo_id, explicacion_correcta) VALUES
('Do you go to the gym every day?', 'No, I didn''t ___ yesterday.', 1, 2, 0, 46, '<b>Gramática:</b> La primera frase está en presente simple (<i>do you go</i>), la segunda en pasado simple negativo (<i>didn''t go</i>).<br><b>Respuesta correcta:</b> go.<br><b>Ejemplos:</b><ul><li>I didn''t go to school yesterday.</li><li>She didn''t go to the meeting last week.</li></ul>'),
('She is reading a book now.', 'Yes, she ___ every night.', 5, 1, 1, 73, '<b>Gramática:</b> La primera frase está en presente continuo (<i>is reading</i>), la segunda en presente simple (<i>reads</i>).<br><b>Respuesta correcta:</b> reads.<br><b>Ejemplos:</b><ul><li>He reads the newspaper every morning.</li><li>My brother reads before bed.</li></ul>'),
('Did you see the movie last night?', 'Yes, I ___ it every weekend.', 2, 1, 1, 74, '<b>Gramática:</b> La primera frase está en pasado simple (<i>did you see</i>), la segunda en presente simple (<i>see</i>).<br><b>Respuesta correcta:</b> see.<br><b>Ejemplos:</b><ul><li>I see my friends every weekend.</li><li>We see the sunrise from here.</li></ul>'),
('He speaks English very well.', 'Does he ___ French too?', 1, 1, 1, 87, '<b>Gramática:</b> Ambas frases están en presente simple (<i>speaks</i>, <i>does he speak</i>).<br><b>Respuesta correcta:</b> speak.<br><b>Ejemplos:</b><ul><li>Does she speak Spanish?</li><li>They speak three languages.</li></ul>'),
('Are you coming to the party?', 'No, I don''t ___ to parties often.', 5, 1, 0, 24, '<b>Gramática:</b> La primera frase está en presente continuo (<i>are you coming</i>), la segunda en presente simple negativo (<i>don''t come</i>).<br><b>Respuesta correcta:</b> come.<br><b>Ejemplos:</b><ul><li>I don''t come here very often.</li><li>We don''t come to this restaurant.</li></ul>'),
('They didn''t eat breakfast this morning.', 'Do they ___ lunch at least?', 2, 1, 0, 32, '<b>Gramática:</b> La primera frase está en pasado simple negativo (<i>didn''t eat</i>), la segunda en presente simple (<i>do they eat</i>).<br><b>Respuesta correcta:</b> eat.<br><b>Ejemplos:</b><ul><li>Do you eat vegetables?</li><li>They eat lunch at noon.</li></ul>'),
('She writes emails every day.', 'Is she ___ one right now?', 1, 5, 1, 100, '<b>Gramática:</b> La primera frase está en presente simple (<i>writes</i>), la segunda en presente continuo (<i>is she writing</i>).<br><b>Respuesta correcta:</b> writing.<br><b>Ejemplos:</b><ul><li>She is writing a letter now.</li><li>Are you writing your homework?</li></ul>'),
('We are not watching TV now.', 'Did you ___ it yesterday?', 5, 2, 0, 38, '<b>Gramática:</b> La primera frase está en presente continuo negativo (<i>are not watching</i>), la segunda en pasado simple (<i>did you watch</i>).<br><b>Respuesta correcta:</b> watch.<br><b>Ejemplos:</b><ul><li>Did you watch the game?</li><li>I watched a movie yesterday.</li></ul>'),
('Did he drive to work yesterday?', 'No, he doesn''t ___ to work.', 2, 1, 0, 31, '<b>Gramática:</b> La primera frase está en pasado simple (<i>did he drive</i>), la segunda en presente simple negativo (<i>doesn''t drive</i>).<br><b>Respuesta correcta:</b> drive.<br><b>Ejemplos:</b><ul><li>He doesn''t drive on weekends.</li><li>Do you drive to school?</li></ul>'),
('I don''t understand this exercise.', 'Did you ___ the last one?', 1, 2, 0, 92, '<b>Gramática:</b> La primera frase está en presente simple negativo (<i>don''t understand</i>), la segunda en pasado simple (<i>did you understand</i>).<br><b>Respuesta correcta:</b> understand.<br><b>Ejemplos:</b><ul><li>Did you understand the lesson?</li><li>I understood everything yesterday.</li></ul>');
